-- BEGIN;

-- INSERT INTO plants_answers (question, answer_text, answer_value)
-- VALUES
--   (16, 'A bright spot', 'high'),
--   (16, 'A shadier spot', 'medium'),
--   (16, 'I can barely read a book', 'low'),
--   (16, 'Artifical lighting only', 'none'),
--   (17, 'Yes', 'yes'),
--   (17, 'No', 'no'),
--   (18, 'On a regular schedule', 'high'),
--   (18, 'I forget from time to time', 'medium'),
--   (18, 'Wait, plants need water?', 'low'),
--   (19, 'Some tablespace', 'tabletop'),
--   (19, 'Small floor space or larger tablespace', 'small'),
--   (19, 'A good space filler', 'meduim'),
--   (19, 'I want a tree!', 'large'),
--   (20, 'Green? Its a bit more of a black thumb', 'beginner'),
--   (20, 'I''ve kept a few plants alive', 'intermediate'),
--   (20, 'I definitely have a green thumb!', 'advanced');

--   COMMIT;