CREATE TABLE plants_base (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cmn_name TEXT,
  sci_name TEXT NOT NULL,
  photo TEXT NOT NULL,
  light TEXT NOT NULL,
  pet_safe TEXT NOT NULL,
  water TEXT NOT NULL,
  size TEXT NOT NULL,
  care_level TEXT NOT NULL
);