CREATE TABLE plants_questions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question TEXT NOT NULL,
  answer_1 TEXT,
  answer_2 TEXT,
  answer_3 TEXT,
  answer_4 TEXT
);



-- CREATE TABLE plants_questions (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   question TEXT NOT NULL,
-- );